# Tokyo Night theme
set -g @tokyo-night-tmux_theme 'night'
set -g @tokyo-night-tmux_show_datetime 1
set -g @tokyo-night-tmux_date_format YMD
set -g @tokyo-night-tmux_time_format 12H
set -g @tokyo-night-tmux_show_battery_widget 1
set -g @tokyo-night-tmux_show_netspeed 1
set -g @plugin 'janoamaral/tokyo-night-tmux'

# Status line
set -g status-position top

# plugins
unbind o
set -g @sessionx-bind 'o'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# window management 
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set-option -g allow-rename off 
set -g mouse on
bind < swap-window -t -1 \; prev
bind > swap-window -t +1 \; next

# Don't prompt to kill pane/window
bind x kill-pane
unbind &
bind X kill-window

bind-key -n S-Enter send-keys Escape "[13;2u"
set -g extended-keys on
set -as terminal-features 'tmux-256color:extkeys'

bind a last-window       # jump back to previous window
bind Tab switch-client -l  # jump back to previous session

# Alt+number to switch windows
bind -n M-0 select-window -t 0
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9

# Alt+hjkl to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# remap prefix 
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind C-k send-keys "clear" Enter \; clear-history

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# vim motion and copy bindings
set -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind Enter copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel


bind c new-window -c "#{pane_current_path}"
bind C command-prompt "new-window -n '%%'"


# Terminal and colors
set -g default-terminal "tmux-256color"
set -sa terminal-features ",xterm-ghostty:RGB"
set -g allow-passthrough on
set -sg escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g history-limit 250000

bind r source-file ~/.tmux.conf \; display "Config reloaded!"




# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
