# vim:set ft=tmux:
# Docker override: docker icon in peach (#fab387)
# See catppuccin-prefix.conf for hex escape reference

set -g @catppuccin_status_prefix \
  "#[fg=#{?client_prefix,#E590A8,#B3E1A7}]#[fg=#11111A,bg=#{?client_prefix,#E590A8,#B3E1A7}]󰌌 #[fg=#{E:@thm_crust},bg=#fab387] 󰡨 #[fg=#fab387,bg=default]#[default] "
